services:
    postgres:
        image: postgres:16.1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 8W0MQwY4DINCoX
            POSTGRES_DB: data-mining
        volumes:
            - ./database:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - "5432:5432"